{
 "title": "Dados Redação Enem 2019 V2",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Maior e Menor Idade dos Candidatos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select MIN(\"NU_IDADE\"::numeric) as Menor_Idade, MAX(\"NU_IDADE\"::numeric) as Maior_Idade\r\nfrom redacao.notas_redacao_tratada_2019"
    }
   ]
  },
  {
   "title": "Quantidade de Participantes por Sexo",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \"TP_SEXO\", count(*)\r\nfrom redacao.notas_redacao_tratada_2019\r\ngroup by \"TP_SEXO\""
    }
   ]
  },
  {
   "title": "Média de Notas por Sexo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "select \"TP_SEXO\", avg(\"NU_NOTA_REDACAO\"::numeric)\r\nfrom redacao.notas_redacao_tratada_2019\r\ngroup by \"TP_SEXO\""
    }
   ]
  },
  {
   "title": "Tabela Completa",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select * from redacao.notas_redacao_tratada_2019"
    }
   ]
  }
 ]
}